
name: Deno

on:
  push:
    branches: ["master"]
    paths:
      - "**.js" # Any JS file
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/node.yml" # This action
  pull_request:
    branches: ["master"]
    paths:
      - "**.js" # Any JS file
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/node.yml" # This action

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21

      - name: Compile
        run: bun build bin/gamedig.js
