
name: Bun

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21

      - name: Compile
        run: bun build bin/gamedig.js
